name: Windows CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-ninja@master
      
      - name: Build the project
        run: .\scripts\build.bat
        shell: batch
      
      - name: Run the tests
        run: .\scripts\run-tests.bat
        shell: batch
